TRAIN_DATASET_PATH: /esat/smcdata/users/kkontras/Image_Dataset/no_backup/Sth-Sth/something_something_detections/kkontras_flow_train.json
VAL_DATASET_PATH: /esat/smcdata/users/kkontras/Image_Dataset/no_backup/Sth-Sth/something_something_detections/kkontras_flow_val.json
TRAIN_DATASET_NAME: something-something
VAL_DATASET_NAME: something-something
LABELS_PATH: /esat/smcdata/users/kkontras/Image_Dataset/no_backup/Sth-Sth/something-something-v2-labels.json
VIDEOS_PATH: /esat/smcdata/users/kkontras/Image_Dataset/no_backup/Sth-Sth/flow_dataset.hdf5
EXPERIMENT_PATH: /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/SthSth/unimodal_flow
DATASET_TYPE: video
TOTAL_ACTIONS: 
  ACTION: 174
ACTION_WEIGHTS: 
  ACTION: 1.0
AUGMENTATIONS:
  FLOW: [ "VideoResize", "VideoRandomCrop" ]
NUM_WORKERS: 5
MODEL_NAME: swin
BATCH_SIZE: 16
FRAME_UNIFORM: True
NUM_FRAMES: 16
WEIGHT_DECAY: 0.02 # As per SWIN paper (Section 4.1)
LEARNING_RATE: 0.0001
EPOCHS: 30
WARMUP_EPOCHS: 3